# Generated by Django 4.0.4 on 2022-08-31 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_video_alter_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_video',
        ),
        migrations.AddField(
            model_name='post',
            name='post_media',
            field=models.FileField(default=django.utils.timezone.now, upload_to='post/post_media'),
            preserve_default=False,
        ),
    ]
