# Generated by Django 4.0.4 on 2022-09-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='privacy',
            field=models.CharField(default='private', max_length=40),
        ),
    ]
