# Generated by Django 4.0.4 on 2022-09-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
